sudo: required
language: generic 
services: 
    - docker

before_install:
    - docker build -t hmstd/docker-react -f Dockerfile.dev .

#script:
#    - docker run hmstd/docker-react npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-2-255510537618"
    bucket_path: "docker-react"
    on:
      branch: master

    access_key_id: "$AWS_ACCESS_KEY"
    secret_access_key: "$AWS_SECRET_KEY"

#access_key_id: 
#    secure: "$AWS_ACCESS_KEY"
#secret_access_key:
#    secure: "$AWS_SECRET_KEY"
