sudo: required
language: generic 
services: 
    - docker

before_install:
    - docker build -t hmstd/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true hmstd/docker-react npm run test